# Generated by Django 5.0.3 on 2024-06-10 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intro_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='text',
            new_name='exampleFormControlTextarea1',
        ),
    ]
