# Generated by Django 5.0.3 on 2024-06-10 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intro_app', '0002_rename_text_form_exampleformcontroltextarea1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='exampleFormControlTextarea1',
            new_name='text',
        ),
    ]
